export type FoodItem = {
  id: string
  name: string
  description: string
  price: number
  discountPrice?: number
  emoji: string
  category: string
  isVeg: boolean
  isBestseller?: boolean
  isSpicy?: boolean
  isAvailable: boolean
}

export const CATEGORIES = [
  { id: 'all', name: 'All', emoji: '🍽️' },
  { id: 'pizza', name: 'Pizza', emoji: '🍕' },
  { id: 'burger', name: 'Burger', emoji: '🍔' },
  { id: 'chinese', name: 'Chinese', emoji: '🥡' },
  { id: 'snacks', name: 'Snacks', emoji: '🍟' },
  { id: 'maincourse', name: 'Main Course', emoji: '🍛' },
  { id: 'biryani', name: 'Biryani', emoji: '🍚' },
  { id: 'beverages', name: 'Beverages', emoji: '🥤' },
  { id: 'desserts', name: 'Desserts', emoji: '🍰' },
  { id: 'special', name: 'Special', emoji: '⭐' },
]

export const FOOD_ITEMS: FoodItem[] = [
  {
    id: 'p1',
    name: 'Farmhouse Pizza',
    description: 'Loaded with onion, capsicum, tomato & mushroom',
    price: 299,
    discountPrice: 249,
    emoji: '🍕',
    category: 'pizza',
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
  },
  {
    id: 'p2',
    name: 'Chicken Tikka Pizza',
    description: 'Tandoori chicken, onion, capsicum with mint mayo',
    price: 379,
    emoji: '🍕',
    category: 'pizza',
    isVeg: false,
    isSpicy: true,
    isAvailable: true,
  },
  {
    id: 'p3',
    name: 'Veg Burger',
    description: 'Crispy veg patty, lettuce, tomato, tangy mayo',
    price: 99,
    emoji: '🍔',
    category: 'burger',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'p4',
    name: 'Chicken Zinger Burger',
    description: 'Crispy fried chicken fillet with spicy mayo',
    price: 159,
    discountPrice: 139,
    emoji: '🍔',
    category: 'burger',
    isVeg: false,
    isBestseller: true,
    isSpicy: true,
    isAvailable: true,
  },
  {
    id: 'p5',
    name: 'Hyderabadi Chicken Biryani',
    description: 'Authentic dum biryani with tender chicken & raita',
    price: 249,
    emoji: '🍚',
    category: 'biryani',
    isVeg: false,
    isBestseller: true,
    isSpicy: true,
    isAvailable: true,
  },
  {
    id: 'p6',
    name: 'Veg Hakka Noodles',
    description: 'Stir-fried noodles with fresh vegetables',
    price: 149,
    emoji: '🍜',
    category: 'chinese',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'p7',
    name: 'Paneer Butter Masala',
    description: 'Creamy tomato gravy with soft paneer cubes',
    price: 219,
    emoji: '🍛',
    category: 'maincourse',
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
  },
  {
    id: 'p8',
    name: 'Masala Chai',
    description: 'Authentic Indian spiced tea',
    price: 49,
    emoji: '☕',
    category: 'beverages',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'p9',
    name: 'Chocolate Brownie',
    description: 'Warm brownie with chocolate sauce',
    price: 129,
    emoji: '🍰',
    category: 'desserts',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'p10',
    name: 'French Fries',
    description: 'Crispy golden fries with peri-peri seasoning',
    price: 89,
    emoji: '🍟',
    category: 'snacks',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'p11',
    name: 'Veg Manchurian',
    description: 'Crispy veg balls in spicy manchurian sauce',
    price: 179,
    emoji: '🥡',
    category: 'chinese',
    isVeg: true,
    isSpicy: true,
    isAvailable: true,
  },
  {
    id: 'p12',
    name: 'Special Family Thali',
    description: 'Complete meal – roti, sabzi, dal, rice, salad & sweet',
    price: 249,
    emoji: '🍽️',
    category: 'special',
    isVeg: true,
    isBestseller: true,
    isAvailable: true,
  },
  {
    id: 'p13',
    name: 'Cold Coffee',
    description: 'Chilled creamy coffee with ice cream',
    price: 89,
    emoji: '🥤',
    category: 'beverages',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'p14',
    name: 'Chicken Momos',
    description: 'Steamed momos with spicy chutney',
    price: 129,
    emoji: '🥟',
    category: 'snacks',
    isVeg: false,
    isAvailable: true,
  },
  {
    id: 'p15',
    name: 'Gulab Jamun',
    description: 'Soft khoya balls in sweet sugar syrup',
    price: 79,
    emoji: '🍮',
    category: 'desserts',
    isVeg: true,
    isAvailable: true,
  },
  {
    id: 'p16',
    name: 'Butter Chicken',
    description: 'Creamy tomato gravy with tender chicken pieces',
    price: 289,
    emoji: '🍗',
    category: 'maincourse',
    isVeg: false,
    isBestseller: true,
    isAvailable: true,
  },
]